### ISSUE TITLE
Kanban Board for ROR Group project

### ISSUE THREAD

**Issue by cosywasswa** [cosywasswa/Foods-App#13]
Here is our kanban board for ROR Group project.
We are a group of 2 people.
link to project. https://github.com/cosywasswa/Foods-App/projects/1

@cosywasswa 
@AJ193

**Comment by TedLivist** [comment]
## STATUS: CHANGES REQUIRED ♻️ ♻️

Hi @cosywasswa and @AJ193,

Good job so far!
✔️ Kanban columns are complete
✔️ Tasks are well assigned
However, there are some issues that you still need to work on to go to the next project but you are almost there!

## Required Changes ♻️
- [ ] Kindly add an issue for this task.

  ![image](https://github.com/cosywasswa/Foods-App/assets/36542986/ae5c2d33-e2ee-497e-8975-38d775f8a117)

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the Issue thread if something is not 100% clear. And please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Issue for re-reviews. You should use the same Issue submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by DammyShittu** [comment]
Hi @cosywasswa and @AJ193,

## APPROVED 🟢

## Highlights
✔️ Descriptive issue

Great implementation of all the requirements in this milestone. 👏 

_You have done an amazing job 👍_

Your project is complete!  There is nothing else to say other than... it's time to merge it. :shipit: 

Congratulations! 🎉 

## CHEERS AND HAPPY CODING!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
